version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: chatbot-postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - chatbot_network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-chatbot
    ports:
      - "127.0.0.1:8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - chatbot_network
  chatbot-auth:
    image: chatbot-auth:latest
    pull_policy: if_not_present
    container_name: chatbot-auth
    ports:
      - "5000:5000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    depends_on:
      - postgres
    networks:
      - chatbot_network
  chatbot-nginx:
    image: chatbot-nginx:latest
    pull_policy: if_not_present
    container_name: chatbot-nginx
    ports:
      - "8888:8888"
    environment:
      NGINX_SERVER: ${NGINX_SERVER_URL}
      RASA_SERVER: ${RASA_SERVER_URL}
      AUTH_SERVER: ${AUTH_SERVER_URL}
    networks:
      - chatbot_network
  rasa-server:
    image: chatbot-rasa:latest
    pull_policy: if_not_present
    container_name: rasa-server
    environment:
      ROLE: rasa
    ports:
      - "127.0.0.1:5005:5005"
    depends_on:
      - chatbot-auth
    volumes:
      - ./chatbot-rasa:/app
  rasa-actions:
    image: chatbot-rasa:latest
    pull_policy: if_not_present
    container_name: rasa-actions
    ports:
      - "127.0.0.1:5055:5055"
    environment:
      ROLE: action
networks:
  chatbot_network:
    driver: bridge