# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20241217-163155-dichotomic-log

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: el


pipeline:
  # - name: "WhitespaceTokenizer"
  # - name: "CountVectorsFeaturizer"
  # - name: "DIETClassifier"
  #   epochs: 100
  #   constrain_similarities: true

# # config for spacyNLP and bert models
  - name: "SpacyNLP"
    model: "el_core_news_md"
    case_sensitive: False
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
    pooling: max
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "nlpaueb/bert-base-greek-uncased-v1"
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: True
  - name: ResponseSelector
    epochs: 100
    retrieval_intent: chitchat
  - name: EntitySynonymMapper
  - name: RegexEntityExtractor
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
  # - name: WhitespaceTokenizer
  # - name: CRFEntityExtractor
  # - name: EntitySynonymMapper
  # - name: RegexFeaturizer
  # - name: LexicalSyntacticFeaturizer
  # - name: CountVectorsFeaturizer
  #   analyzer: char_wb
  #   min_ngram: 1
  #   max_ngram: 4
  # - name: DIETClassifier
  #   entity_recognition: false
  #   epochs: 100
  #   constrain_similarities: true
  # - name: EntitySynonymMapper
  # - name: ResponseSelector
  #   epochs: 100
  #   constrain_similarities: true
  # - name: FallbackClassifier
  #   threshold: 0.3
  #   ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: UnexpecTEDIntentPolicy
    epochs: 100
    max_history: 8
  - name: RulePolicy
    core_fallback_threshold: 0.7
    core_fallback_action_name: action_default_fallback
    enable_fallback_prediction: true
    check_for_contradictions: true
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: RulePolicy
#   - name: UnexpecTEDIntentPolicy
#     max_history: 5
#     epochs: 100
