FROM rasa/rasa-sdk:3.6.2

WORKDIR /app

COPY actions actions
COPY requirements-actions.txt requirements.txt

USER root

RUN python -m pip install --no-cache-dir -r requirements.txt && \
    chown 1001:1001 /app -R

USER 1001

EXPOSE 5055

ENTRYPOINT ["./entrypoint.sh"]
